#!/bin/sh
# Copyright (C) 2013-2016 Sören Tempel
# Copyright (C) 2016, 2017 Klemens Nanni <kl3@posteo.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e
umask u=rwx,go=

## Variables
GPG_OPTS='--quiet --yes --batch'
STORE_DIR="${PASSWORD_STORE_DIR:-${HOME}/.spm}"

## Helper
usage() {
	cat 1>&2 <<-EOF
	${1:+Error: ${1}}
	USAGE: ${0##*/} add|del|list [-g]|search|show|help [[group/]entry|expression]
	See spm(1) for more information.
	EOF

	exit ${1:+1}
}

check() {
	[ -n "${entry}" ] || usage 'no such entry'

	[ $(printf '%s' "${entry}" | wc -l) -eq 0 ] ||
		usage 'ambigious expression'
}

gpg() {
	if [ -z "${PASSWORD_STORE_KEY}" ]; then
		gpg2 ${GPG_OPTS} --default-recipient-self "${@}"
	else
		gpg2 ${GPG_OPTS} --recipient "${PASSWORD_STORE_KEY}" "${@}"
	fi
}

readpw() {
	if [ -t 0 ]; then
		stty -echo
		printf '%s' "${1}"
	fi
	IFS= read -r "${2}"
	if [ -t 0 ]; then
		stty echo
		printf '\n'
	fi
	if [ -z "${2}" ]; then
		usage 'empty password'
	fi
}

find() {
	command find "${STORE_DIR}" -type f -o -type l | grep -Gie "${1}"
}

munge() {
	abspath="$(readlink -f "${STORE_DIR}"/"${1}")"
	case "${abspath}" in
	"${STORE_DIR}"*)
		eval ${2}=\"${abspath#${STORE_DIR}}\"
		;;
	*)
		usage 'bad traversal'
	esac
}

view() {
	less -EiKRX
}

## Commands
add() {
	if [ -e "${STORE_DIR}"/"${1}" ]; then
		usage 'entry already exists'
	fi

	password=
	readpw "Password for '${1}': " password
	if [ -t 0 ]; then
		printf '\n'
	fi

	group="${1%/*}"
	if [ "${group}" = "${1}" ]; then
		group=
	fi

	mkdir -p "${STORE_DIR}"/"${group}" &&
		printf '%s\n' "${password}" |
			gpg --encrypt --output "${STORE_DIR}"/"${1}"
}

list() {
	[ -d "${STORE_DIR}"/"${1:-}" ] || usage 'no such group'

	if [ -t 1 ]; then
		tree ${gflag:+-d} -Fx -- "${STORE_DIR}"/"${1:-}" | view
	elif [ -n "$gflag" ]; then
		(cd ${STORE_DIR}; command find * -type d)
	else
		(cd ${STORE_DIR}; command find * -type f)
	fi
}

del() {
	entry=$(find "${1}" | head -n2)
	check; command rm -i "${entry}" && printf '\n'
}

search() {
	find "${1}" | view
}

show() {
	entry=$(find "${1}" | head -n2)
	check; gpg --decrypt "${entry}"
}

## Parse input
if [ ${#} -eq 0 ] || [ ${#} -gt 3 ] ||
	[ ${#} -eq 3 ] && [ "${1:-}" != list ]; then
	usage 'wrong number of arguments'
fi

case "${1}" in
add|del|search|show)
	if [ -z "${2:-}" ]; then
		usage 'empty name'
	fi
	${1} "${2}"
	;;
list)
	if [ "${2:-}" = -g ] && gflag=1; then
		shift 1
	fi
	if [ ${#} -gt 2 ]; then
		usage 'too many arguments'
	fi
	if [ -n "${2:-}" ]; then
		munge "${2}" relpath
	fi
	list "${relpath:-}"
	;;
help)
	usage
	;;
*)
	usage 'invalid command'
	;;
esac
